import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Cubeforge',
  description: 'React-first 2D browser game engine',
  appearance: true,
  base: '/cubeforge/',
  themeConfig: {
    logo: '/logo.svg',
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'API', link: '/api/game' },
      { text: 'Examples', link: 'https://1homsi.github.io/cubeforge-examples/' },
      { text: 'Playground', link: 'https://1homsi.github.io/cubeforge-playground/' },
      { text: 'GitHub', link: 'https://github.com/1homsi/cubeforge' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'What is Cubeforge?', link: '/guide/what-is-cubeforge' },
            { text: 'Getting Started', link: '/guide/getting-started' },
          ],
        },
        {
          text: 'Core Concepts',
          items: [
            { text: 'ECS', link: '/guide/ecs' },
            { text: 'Physics', link: '/guide/physics' },
            { text: 'Rendering', link: '/guide/rendering' },
            { text: 'Input', link: '/guide/input' },
            { text: 'Tilemaps', link: '/guide/tilemaps' },
          ],
        },
        {
          text: 'Advanced',
          items: [
            { text: 'DevTools & Deterministic Mode', link: '/guide/devtools' },
            { text: 'Renderers (WebGL2 / Canvas2D)', link: '/guide/webgl-renderer' },
            { text: 'Multiplayer', link: '/guide/multiplayer' },
            { text: 'Embedding in React Apps', link: '/guide/embedding' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'Components',
          items: [
            { text: 'Game', link: '/api/game' },
            { text: 'World', link: '/api/world' },
            { text: 'Entity', link: '/api/entity' },
            { text: 'Transform', link: '/api/transform' },
            { text: 'Sprite', link: '/api/sprite' },
            { text: 'Text', link: '/api/text' },
            { text: 'RigidBody', link: '/api/rigidbody' },
            { text: 'BoxCollider', link: '/api/boxcollider' },
            { text: 'CircleCollider', link: '/api/circle-collider' },
            { text: 'CapsuleCollider', link: '/api/capsule-collider' },
            { text: 'Script', link: '/api/script' },
            { text: 'Camera2D', link: '/api/camera2d' },
            { text: 'CameraZone', link: '/api/camera-zone' },
            { text: 'Animation', link: '/api/animation' },
            { text: 'Trail', link: '/api/trail' },
            { text: 'ParticleEmitter', link: '/api/particle-emitter' },
            { text: 'SquashStretch', link: '/api/squash-stretch' },
            { text: 'ParallaxLayer', link: '/api/parallax-layer' },
            { text: 'MovingPlatform', link: '/api/moving-platform' },
            { text: 'Checkpoint', link: '/api/checkpoint' },
            { text: 'Tilemap', link: '/api/tilemap' },
            { text: 'ScreenFlash', link: '/api/screen-flash' },
            { text: 'VirtualJoystick', link: '/api/virtual-joystick' },
            { text: 'AssetLoader', link: '/api/asset-loader' },
          ],
        },
        {
          text: 'Hooks',
          items: [
            { text: 'usePlatformerController', link: '/api/use-platformer-controller' },
            { text: 'useTopDownMovement', link: '/api/use-top-down-movement' },
            { text: 'useGame', link: '/api/use-game' },
            { text: 'useEntity', link: '/api/use-entity' },
            { text: 'useDestroyEntity', link: '/api/use-destroy-entity' },
            { text: 'useHealth', link: '/api/use-health' },
            { text: 'useDamageZone', link: '/api/use-damage-zone' },
            { text: 'useAnimationController', link: '/api/use-animation-controller' },
            { text: 'usePersistedBindings', link: '/api/use-persisted-bindings' },
            { text: 'useVirtualInput', link: '/api/virtual-joystick' },
            { text: 'useInput', link: '/api/use-input' },
            { text: 'useInputMap', link: '/api/use-input-map' },
            { text: 'useInputContext', link: '/api/use-input-context' },
            { text: 'usePlayerInput', link: '/api/use-player-input' },
            { text: 'useLocalMultiplayer', link: '/api/use-local-multiplayer' },
            { text: 'useInputRecorder', link: '/api/use-input-recorder' },
            { text: 'useCamera', link: '/api/use-camera' },
            { text: 'useCoordinates', link: '/api/use-coordinates' },
            { text: 'useEvent', link: '/api/use-event' },
            { text: 'useTriggerEnter / useTriggerExit', link: '/api/use-trigger' },
            { text: 'useCollisionEnter / useCollisionExit', link: '/api/use-collision' },
            { text: 'useCircleEnter / useCircleExit', link: '/api/use-circle' },
            { text: 'useKinematicBody', link: '/api/use-kinematic-body' },
            { text: 'useDropThrough', link: '/api/use-drop-through' },
            { text: 'useSound', link: '/api/use-sound' },
            { text: 'useGamepad', link: '/api/use-gamepad' },
            { text: 'usePause', link: '/api/use-pause' },
            { text: 'usePreload', link: '/api/use-preload' },
            { text: 'useSave', link: '/api/use-save' },
            { text: 'usePathfinding', link: '/api/use-pathfinding' },
            { text: 'useAISteering', link: '/api/use-ai-steering' },
            { text: 'useLevelTransition', link: '/api/use-level-transition' },
            { text: 'useGameStateMachine', link: '/api/use-game-state-machine' },
            { text: 'useRestart', link: '/api/use-restart' },
            { text: 'useSnapshot', link: '/api/use-snapshot' },
          ],
        },
        {
          text: 'Utilities',
          items: [
            { text: 'tween', link: '/api/tween' },
            { text: 'createAtlas', link: '/api/create-atlas' },
            { text: 'createInputMap', link: '/api/create-input-map' },
            { text: 'findByTag', link: '/api/find-by-tag' },
            { text: 'Spatial Queries', link: '/api/spatial-queries' },
            { text: 'createTimer', link: '/api/create-timer' },
            { text: 'Audio Groups', link: '/api/audio-groups' },
            { text: 'definePlugin', link: '/api/define-plugin' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/1homsi/cubeforge' },
    ],
    search: { provider: 'local' },
    footer: {
      message: 'MIT License',
      copyright: 'Copyright © 2025 1homsi',
    },
  },
})
